name: optum_gen_ai_chatbot_template
description: ''
version: '1.0'
author: sumitpaul@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: optumgenaichatbottemplate
  parentArtefactID: sumitpaulprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-10-03 01:38:26'
pipelines:
  pipelines/data_vectorize:
    name: data_vectorize
    description: ''
    author: sumitpaul@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-03 01:38:26'
    datasets:
      inputs:
      - datasets/content_vectorized
      - datasets/web_scrape
      outputs:
      - datasets/content_vectorized
      - datasets/web_vectors
    subgraphs: []
    dependencies: {}
  pipelines/chatbot-live:
    name: chatbot-live
    description: ''
    author: sumitpaul@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-10-03 11:28:40'
    datasets:
      inputs:
      - datasets/content_vectorized
      - datasets/get_queries_msk
      outputs:
      - datasets/bot_message
    subgraphs: []
    dependencies: {}
datasets:
  datasets/content_vectorized:
    name: content_vectorized
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:18:21'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Database
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:18:21'
  datasets/web_vectors:
    name: web_vectors
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:24:07'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Warehouse
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:24:07'
  datasets/web_scrape:
    name: web_scrape
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 11:36:38'
    mode: batch
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 11:36:38'
  datasets/bot_message:
    name: bot_message
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-03 13:52:46'
    mode: stream
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: Database
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-03 13:52:46'
  datasets/get_queries_msk:
    name: get_queries_msk
    description: ''
    author: sumitpaul@prophecy.io
    createdAt: '2023-10-04 15:50:54'
    mode: stream
    physicalDatasets:
      sumit-dev-dbx:
        fabricId: 42
        datasetType: File
        description: ''
        author: sumitpaul@prophecy.io
        createdAt: '2023-10-04 15:50:54'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/OpenAI:
      name: OpenAI
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/OpenAISpec.py
      createdAt: '2023-10-03 10:32:26'
    gems/pinecone:
      name: pinecone
      category: Source/Target
      subCategory: Warehouse
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/PineconeFormatSpec.py
      createdAt: '2023-10-03 10:33:49'
    gems/PineconeLookup:
      name: PineconeLookup
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/PineconeLookup.py
      createdAt: '2023-10-03 10:34:45'
    gems/TextProcessing:
      name: TextProcessing
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/TextProcessing.py
      createdAt: '2023-10-03 10:35:37'
    gems/Watermark:
      name: Watermark
      category: Transform
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - sumitpaulprophecyioteam_optumgenaichatbottemplate/gems/Watermark.py
      createdAt: '2023-10-03 10:38:21'
functions:
  author: null
  createdAt: '2023-10-03 01:38:26'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: pypi
  id: 8Gc6e
  name: Prophecy Spark AI (Python)
  enabled: false
  package: prophecy-spark-ai==0.1.8
projectDependencies:
  '34937':
    projectUID: 34937
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34937.git&subPath=
    version: 0.0.1
    isDefault: true
    author: null
    createdAt: '2023-10-11 14:52:24'
  '34935':
    projectUID: 34935
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34935.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-10-11 14:52:24'
  '34936':
    projectUID: 34936
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34936.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-11 14:52:24'
pipelineConfigurations: {}
